name: CI

on:
  push:
    paths-ignore:
    - 'docs/**'
  pull_request:
    paths-ignore:
    - 'docs/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install MLCube
        run: |
          cd mlcube
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel
          pip install dist/mlcube*.whl
      - name: Test MLCube CLI
        run: |
          cd mlcube
          pytest
      - name: Install MLCube Docker Runner
        run: |
          cd runners/mlcube_docker
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel
      - name: Test MLCube Docker CLI
        run: |
          cd runners/mlcube_docker
          pytest
      - name: Install MLCube Singularity Runner
        run: |
          cd runners/mlcube_singularity
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel
      - name: Test MLCube Singularity CLI
        run: |
          cd runners/mlcube_singularity
          pytest
      - name: Install MLCube SSH Runner
        run: |
          cd runners/mlcube_ssh
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel
      - name: Test MLCube SSH CLI
        run: |
          cd runners/mlcube_ssh
          pytest
      - name: Install MLCube Kubernetes Runner
        run: |
          cd runners/mlcube_k8s
          python setup.py install
      - name: Test MLCube Kubernetes CLI
        run: |
          cd runners/mlcube_k8s
          pytest
      - name: Install MLCube GCP Runner
        run: |
          cd runners/mlcube_gcp
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel
      - name: Test MLCube GCP CLI
        run: |
          cd runners/mlcube_gcp
          pytest
      - name: Install MLCube Kubeflow Runner
        run: |
          cd runners/mlcube_kubeflow
          python setup.py install
      - name: Test MLCube Kubeflow CLI
        run: |
          cd runners/mlcube_kubeflow
          pytest