name: Build & Deploy Docs Site (on-merge)

on:
  push:
    paths:
    - 'docs/**'
    - '.github/workflows/docs-site.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mkdocs-requirements.txt
      - name: Build Docs
        working-directory: './'
        run: |
          mkdocs build --theme material \
                --site-dir ../site/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.5.6
        with:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          allow_empty_commit: true
